### ISSUE TITLE
Toggle between SOCD methods?

### ISSUE THREAD

**Issue by piuzera** [passinglink/passinglink#13]
~~Is there a way to do this currently? I've noticed that the stm32f4_disco has this function, but I can't get it to work on pl_bluepill~~

~~Thanks for this awesome project, by the way!~~

Got that first part figured out, sorry!

Is there a way to switch between SOCD methods or is this still a planned feature? I took a glance at the code and saw that there's mentions of it. I wanted to have a GPIO input that switches between SOCD = Neutral or Last Direction Wins.

Thanks again!

**Comment by jmgao** [comment]
I implemented it [here](https://github.com/passinglink/passinglink/commit/bd907a14e2f09b455bc072f18f320d607408aef0), but it hasn't been merged into master yet because I had some rebasing to do, IIRC.

I need to rework the input system to make the giant nest of ifdefs for mode switches that may or may not be there cleaner, but it should be relatively straightforward to add a mode switch that controls the SOCD mode.

**Comment by piuzera** [comment]
I shall wait for the merge to master then, since it may come with other features and whatnot.

Again, thanks for this! It has helped me quite a lot on prototyping some boards for myself.
